name: bagaer  
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+24

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  badges: ^3.1.2
  flutter_screenutil: ^5.9.3
  firebase_messaging: ^15.2.6
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.6.2
  flutter_local_notifications: ^17.0.0
  dio: ^5.7.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.0.3
  intl: ^0.20.2
  pub_semver: ^2.2.0
  lottie: ^3.3.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.0.11
  country_code_picker: ^3.4.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  flutter_svg: ^2.0.9
  webview_flutter: ^4.10.0
  sms_autofill: ^2.4.0
  rive: ^0.14.0
  shimmer: ^3.0.0
  ffmpeg_kit_flutter_new_min_gpl: ^2.1.1
  gallery_saver_plus: ^3.2.9
  sqflite: ^2.4.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image_cropper: ^9.1.0
  http_parser: ^4.0.2
  fpdart: ^1.1.0
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/horizon_logo.png

    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/logos/
    - assets/i18n/
    - assets/avatar/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

# flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  adaptive_icon_background: "#284686"
  adaptive_icon_foreground: "assets/images/icon.png"
  icon_size: 1024

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android: true
  ios: false
